import { describe, it, expect, vi } from 'vitest';
import { SummarySyncService } from '../summary-sync.service';

describe('SummarySyncService', () => {
  it('should process missing list generated by detector and save to repository', async () => {
    // TDD for synchronization loop execution.
    const fakeMissing = [
      { type: 'monthly', startDate: new Date(), endDate: new Date(), label: 'Test Label' }
    ];

    const mockDetector = {
      getAllMissing: vi.fn().mockResolvedValue(fakeMissing)
    };

    const mockGenerator = {
      // Return a generator as expected
      generate: async function* () {
        yield 'STATUS:thinking_via_test-model';
        yield 'Here is your monthly summary!';
      }
    };

    const mockRepo = {
      save: vi.fn().mockResolvedValue({})
    };

    const service = new SummarySyncService(
      mockDetector as any, 
      mockGenerator as any, 
      mockRepo as any
    );

    const callbacks = {
      onProgress: vi.fn(),
      onCompleted: vi.fn(),
      onError: vi.fn()
    };

    await service.syncMissingSummaries(callbacks);

    expect(mockDetector.getAllMissing).toHaveBeenCalled();
    expect(callbacks.onProgress).toHaveBeenCalledWith(fakeMissing[0], 'thinking_via_test-model');
    expect(mockRepo.save).toHaveBeenCalled();
    // Validate save body properties implicitly
    const saveCallArg = mockRepo.save.mock.calls[0][0];
    expect(saveCallArg.content).toBe('Here is your monthly summary!');
    
    expect(callbacks.onCompleted).toHaveBeenCalled();
    expect(callbacks.onError).not.toHaveBeenCalled();
  });
});
